title: Sangho Lee
subtitle: 이상호
face: /assets/img/sangho.jpg
cv: /assets/cv/sangholee_cv.pdf
description: Ph.D student in CSE at Seoul National University
location: Seoul, South Korea
email: sangho.lee AT vision.snu.ac.kr
homepage: https://sangho-vision.github.io
github: https://github.com/sangho-vision
linkedin: https://www.linkedin.com/in/sanghol
google_scholar: https://scholar.google.com/citations?hl=ko&user=Lq8MN6wAAAAJ
theme: jekyll-theme-minimal
