title: Sangho Lee
subtitle: 이상호
face: /assets/img/sangho.jpg
cv: https://drive.google.com/open?id=1lCb0NtmINd4KnfotjcTqysd85pTmPpPx
description: Ph.D student in CSE at Seoul National University
location: Seoul, South Korea
email: sangho.lee AT vision.snu.ac.kr
homepage: https://sangho-vision.github.io
github: https://github.com/sangho-vision
theme: jekyll-theme-minimal
